"""Public API for the dependency-free Prime Axis Engine."""

__version__ = "1.0.0"

from .engine import (
    AxisResult,
    AxisSpec,
    AxisStatus,
    AxisTick,
    ClockRegressionError,
    EngineConfig,
    EngineError,
    EngineTick,
    SimulationEngine,
    SimulationResult,
    default_axis_specs,
)
from .geometry import (
    DescentReport,
    DescentWitness,
    MAX_EXACT_QUOTIENT_ORDER,
    accumulate_cocycle,
    analyze_quotient_descent,
    circular_distance,
    cocycle_increment,
    compose_cocycle,
    evaluate_closure,
    make_geometry_snapshot,
    normalize_phase,
    quotient_label,
    return_residual,
)
from .ledger import (
    AuditIssue,
    AuditReport,
    DurabilityPolicy,
    LedgerWriter,
    SCHEMA_VERSION,
    audit_ledger,
    canonical_json,
)
from .model import (
    AxisSnapshot,
    ClockSnapshot,
    ClosureStatus,
    GeometrySnapshot,
    MultiAxisTickEvent,
    Severity,
    TickEvent,
)
from .number_theory import divisor_count, is_prime
from .routing import (
    InvalidRouteRequest,
    MoveName,
    PrimeRoutePlanner,
    RouteMode,
    RouteNotFound,
    RoutePlanningError,
    RouteResult,
    RouteStep,
    SearchLimitExceeded,
    allowed_moves,
    node_friction,
)

__all__ = [
    "AuditIssue",
    "AuditReport",
    "AxisResult",
    "AxisSnapshot",
    "AxisSpec",
    "AxisStatus",
    "AxisTick",
    "ClockRegressionError",
    "ClockSnapshot",
    "ClosureStatus",
    "DurabilityPolicy",
    "DescentReport",
    "DescentWitness",
    "EngineConfig",
    "EngineError",
    "EngineTick",
    "GeometrySnapshot",
    "InvalidRouteRequest",
    "LedgerWriter",
    "MAX_EXACT_QUOTIENT_ORDER",
    "MoveName",
    "MultiAxisTickEvent",
    "PrimeRoutePlanner",
    "RouteMode",
    "RouteNotFound",
    "RoutePlanningError",
    "RouteResult",
    "RouteStep",
    "SCHEMA_VERSION",
    "SearchLimitExceeded",
    "Severity",
    "SimulationEngine",
    "SimulationResult",
    "TickEvent",
    "__version__",
    "accumulate_cocycle",
    "analyze_quotient_descent",
    "allowed_moves",
    "audit_ledger",
    "canonical_json",
    "circular_distance",
    "cocycle_increment",
    "compose_cocycle",
    "default_axis_specs",
    "divisor_count",
    "evaluate_closure",
    "is_prime",
    "make_geometry_snapshot",
    "node_friction",
    "normalize_phase",
    "quotient_label",
    "return_residual",
]
